spring:
  application:
    name: InsuranceReportGenerationApplication-2
  datasource:
    url: jdbc:mysql://localhost:3306/policy
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  jpa:
    hibernate:
     ddl-auto : update
    show-sql: true
  
  mvc:
    view:
      prefix: /webapp/
      suffix: .jsp

 